minor changes
firebase/firebase-jobdispatcher-android pull request #47
Opened 2016-11-08 14:48 UTC by anasanasanas

2016-11-08 17:54 UTC, anasanasanas commented
I signed it!

2016-11-13 09:36 UTC, anasanasanas commented
I updated the GitHub account in CLA.

2016-12-15 21:44 UTC, ciarand requested changes
Can you add a test for this?

2016-12-15 21:44 UTC, ciarand commented on jobdispatcher/src/main/java/com/firebase/jobdispatcher/DefaultJobValidator.java
> +        if (extras == null){
nit: extra space after the )

2020-04-07 21:06 UTC, samtstern commented
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and improve it with this Pull Request.  We sincerely appreciate your effort and we apologize for not addressing it in time.

2020-04-07 21:06 UTC, closed without merging